# Generated by Django 3.2.6 on 2022-05-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drowsy', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
