# Generated by Django 3.2.6 on 2022-05-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.data')),
            ],
            bases=('api.data',),
        ),
    ]
