# Generated by Django 3.2.6 on 2022-05-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
