# Generated by Django 3.2.6 on 2022-05-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_videomodel_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
